### ISSUE TITLE
Final TODO list

### ISSUE THREAD

**Issue by tehKaiN** [Last-Minute-Creations/AMIner#18]
## New stuff

- [x] Add base with portal
  - [x] Rebuilding portal - collect pieces
- [x] Radio transmissions in HUD
  - [x] Portrait thingy for in-game messages from crew and other NPCs
  - [x] radio thingy for getting transmission from beyond
    - [x] sending message(s) in a loop
    - [x] definable percentage of interference
    - [x] should interference change have effect during transmission or before displaying current message in a loop?
- [ ] Add base after portal or just static screen after warp for outro
- [x] Write down the plot line in a consistent way
- [x] Proper credits screen with names:
  - [ ] Rav.En - tests
  - [ ] Adinfo & son - tests, dino idea, earth core idea
  - [ ] Nuta & Vikto - RK2018 tests
  - [ ] Licenses of 3rd party libs - ptplayer
  - [ ] Recedent for proofreading
  - [ ] Mschulz, Krashan and Asman - help during ptplayer translation to C
- [x] Add fall damage
  - [x] Change machine gfx depending on destruction state
  - [x] Final crash + smoke on hull = 0
  - [x] Add "lives" limit
  - [x] Add explosion
- [x] better balance of plans
- [x] more jet flame variety
- [x] drill power / durability upgrades
- [x] add drill arm movement
- [ ] plan should display alternative cash goal (?)
- [x] Add music playback
- [x] Hi score stuff
  - [x] Cursor when typing hi score
  - [x] Shift button support when typing name in hi-score
  - [x] Saving scores to file
  - [x] Score penalty in challenge after teleport
  - [x] Negative score for always being able to refuel in free play
- [ ] Add basic AI for 1 player challenge mode
- [x] ACE
  - [x] `fileOpen()` should return 0 if opened to write and disk is write protected
  - [x] implement `fileIsProtected()`
- [x] Game endings
  - [x] Game over when out of lives
  - [x] Gate ending(s)
  - [x] Plan solver ending
- [x] Mode selection
  - [x] Add menu for selecting drill/tnt/nuke/teleport modes
  - [x] Implement drill mode
  - [x] Implement tnt mode
  - [x] Implement teleport mode
  - [ ] Implement nuke mode
- [x] Rocks & TNTs
  - [ ] TNTs should give player mineral from rock
  - [x] Drilling through rock (also with gems) should be doable but slow
  - [ ] Drill upgrades should allow players to drill through rock faster
- [x] Add "office" tab
  - [x] Add selection of NPC
  - [x] Add support for dialogue options
  - [x] Add support for more plan time
  - [x] Add support for regenerating plan
  - [ ] Add support for random buy offers
- [x] Menu
  - [x] Use commrade screen to display it
- [ ] Add date counter

## Bugfixes

- [x] sfx is spammed sometimes during refuel (less money than required to do full restock?)
- [x] Message system introduced crashes during OS use/unuse - add osflush in ACE - related to https://github.com/AmigaPorts/ACE/issues/76
- [x] Remove garbage on screen just after loading main viewport
- [x] Fix ADF generation - started to work again without any fix, wtf
- [x] better RNG for tiles - related to https://github.com/AmigaPorts/ACE/issues/64
- [ ] add red wheels to red player or redraw them to be player-agnostic
- [x] Do something with lack of alpha on Commrade edges
- [x] Loading after logo and before menu is a long black screen when run from floppy
- [x] Loading after menu and start looks like the game has frozen when run from floppy
- [x] Fix "press button to continue" message in hi score display
- [ ] Wheels are not spinning when digging left/right
